### ISSUE TITLE
FE Refactor: decouple components

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#23]
decoupling components for iteration 2 due to model design mismatch against backend

Folder Structure (frontend):
```
components/
  CreateMemo/
      components/
      ...
  Profile/
  ...
pages/
   MainPage.tsx
   EntryPage.tsx
   ...
models/
controllers/
```

**Comment by Toastjpg** [comment]
Priority list

1. Reorganize current code into a reasonable folder structure
2. Clean and make use of reasonable types across entire code base (instead of slapping any on everything or ignoring ts errors)
3. Refactor code and introduce proper modularity of components (example: the header rn is copy pasted instead of a component??)
4. Start on fixing features
